spring.application.name=ozhuku-server

ozhuku.storage.root=./workspace

spring.datasource.url=jdbc:postgresql://localhost:5432/ozhuku
spring.datasource.username=ozhuku
spring.datasource.password=ozhuku-local
spring.datasource.driver-class-name=org.postgresql.Driver